---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mcloud.infraboard
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcloud.infraboard
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - mcloud.infraboard
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mpaas.mdevcloud.com
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mpaas.mdevcloud.com
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - mpaas.mdevcloud.com
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
